# Generated by Django 4.2.6 on 2023-10-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_alter_donation_latitude_alter_donation_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='daira',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='daira',
        ),
    ]
