# Generated by Django 4.2.6 on 2023-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0003_remove_deposit_daira_remove_donation_daira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
