# Generated by Django 4.2.6 on 2023-10-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0004_alter_deposit_latitude_alter_deposit_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
