# Generated by Django 4.2.6 on 2023-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0005_deposit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='wait_for_vol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
