# Generated by Django 4.2.6 on 2023-10-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0006_donation_wait_for_vol_alter_deposit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Acceptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_accepted', models.BooleanField(default=False)),
                ('deposit_accepted', models.BooleanField(default=False)),
                ('deposit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caps.deposit')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caps.donation')),
            ],
        ),
    ]
