# Generated by Django 4.2.6 on 2023-10-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0009_acceptation_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptation',
            name='deposit_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
