# Generated by Django 4.2.6 on 2023-10-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('donator', 'Donator'), ('deposit', 'Deposit'), ('volunteer', 'Volunteer')], default='donator', max_length=20),
        ),
    ]
